// <auto-generated>
// This file is referenced as external source. Do not modify.
// </auto-generated>

// Copyright (c) 2022 XstarS
// This file is released under the MIT License.
// https://opensource.org/licenses/MIT

namespace global

// Indicates whether this assembly is compliant
// with the Common Language Specification (CLS).
[<assembly: System.CLSCompliant(true)>]
do ()
