// <auto-generated>
// This file is referenced as external source. Do not modify.
// </auto-generated>

// Copyright (c) 2025 XstarS
// This file is released under the MIT License.
// https://opensource.org/licenses/MIT

#pragma warning disable
#nullable enable

#if !(EXCEPTION_THROW_IF_EXTERNAL || NETCOREAPP6_0_OR_GREATER)
namespace System
{
    using System.ComponentModel;
    using System.Diagnostics;
    using System.Diagnostics.CodeAnalysis;
    using System.Runtime.CompilerServices;

    [DebuggerNonUserCode, ExcludeFromCodeCoverage]
    [EditorBrowsable(EditorBrowsableState.Never)]
    [Obsolete("This type supports the `ArgumentNullException.ThrowIf*` methods " +
              "for early frameworks and should not be used directly in user code.")]
    internal static class ArgumentNullExceptions
    {
        extension(ArgumentNullException)
        {
            /// <summary>
            /// Throws an <see cref="ArgumentNullException"/>
            /// if the given <paramref name="argument"/> is <see langword="null"/>.
            /// </summary>
            /// <param name="argument">The reference type argument to validate as non-null.</param>
            /// <param name="paramName">The name of the parameter with which
            /// <paramref name="argument"/> corresponds. If you omit this parameter,
            /// the name of <paramref name="argument"/> is used.</param>
            /// <exception cref="ArgumentNullException">
            /// <paramref name="argument"/> is <see langword="null"/>.</exception>
            public static void ThrowIfNull(object? argument,
                [CallerArgumentExpression(nameof(argument))] string? paramName = null)
            {
                [DoesNotReturn, MethodImpl(MethodImplOptions.NoInlining)]
                static void Throw(string? paramName) =>
                    throw new ArgumentNullException(paramName);
                if (argument is null) { Throw(paramName); }
            }
        }
    }
}
#endif

#if !(EXCEPTION_THROW_IF_EXTERNAL || NETCOREAPP7_0_OR_GREATER)
namespace System
{
    using System.ComponentModel;
    using System.Diagnostics;
    using System.Diagnostics.CodeAnalysis;
    using System.Runtime.CompilerServices;

    [DebuggerNonUserCode, ExcludeFromCodeCoverage]
    [EditorBrowsable(EditorBrowsableState.Never)]
    [Obsolete("This type supports the `ObjectDisposedException.ThrowIf*` methods " +
              "for early frameworks and should not be used directly in user code.")]
    internal static class ObjectDisposedExceptions
    {
        extension(ObjectDisposedException)
        {
            /// <summary>
            /// Throws an <see cref="ObjectDisposedException"/>
            /// if the specified <paramref name="condition"/> is <see langword="true"/>.
            /// </summary>
            /// <param name="condition">The condition to evaluate.</param>
            /// <param name="instance">The object whose type's full name
            /// should be included in any resulting <see cref="ObjectDisposedException"/>.</param>
            /// <exception cref="ObjectDisposedException">
            /// The <paramref name="condition"/> is <see langword="true"/>.</exception>
            public static void ThrowIf(bool condition, object instance)
            {
                [DoesNotReturn, MethodImpl(MethodImplOptions.NoInlining)]
                static void Throw(object instance) =>
                    throw new ObjectDisposedException(instance?.GetType().FullName);
                if (condition) { Throw(instance); }
            }

            /// <summary>
            /// Throws an <see cref="ObjectDisposedException"/>
            /// if the specified <paramref name="condition"/> is <see langword="true"/>.
            /// </summary>
            /// <param name="condition">The condition to evaluate.</param>
            /// <param name="type">The type whose full name
            /// should be included in any resulting <see cref="ObjectDisposedException"/>.</param>
            /// <exception cref="ObjectDisposedException">
            /// The <paramref name="condition"/> is <see langword="true"/>.</exception>
            public static void ThrowIf(bool condition, Type type)
            {
                [DoesNotReturn, MethodImpl(MethodImplOptions.NoInlining)]
                static void Throw(Type type) =>
                    throw new ObjectDisposedException(type?.FullName);
                if (condition) { Throw(type); }
            }
        }
    }
}
#endif

#if !(EXCLUDE_FROM_CODE_COVERAGE_ATTRIBUTE || NETCOREAPP3_0_OR_GREATER)
#if !(NET40_OR_GREATER || NETCOREAPP2_0_OR_GREATER || NETSTANDARD2_0_OR_GREATER)
namespace System.Diagnostics.CodeAnalysis
{
    // Excludes the attributed code from code coverage information.
    internal sealed partial class ExcludeFromCodeCoverageAttribute : Attribute
    {
    }
}
#endif
#endif
